/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nrUO8T1y5L4
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    <div className="relative overflow-hidden w-full h-[100vh] bg-gradient-to-b from-blue-100 to-blue-200 dark:from-gray-700 dark:to-gray-900">
      <div className="container flex flex-col gap-4 px-4 py-12 md:py-24 items-center justify-center text-center mx-auto">
        <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl lg:text-7xl">Weather Forecast</h1>
        <p className="max-w-[600px] text-gray-800 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
          Enter your ZIP code to get the latest weather forecast for your area.
        </p>
        <div className="flex flex-col gap-2 min-[400px]:flex-row">
          <div className="flex flex-col gap-1 min-[400px]:flex-row]">
            <Input className="max-w-xs" placeholder="Enter your ZIP code" />
            <Button className="w-full max-w-xs" size="md">
              Get Weather
            </Button>
          </div>
        </div>
      </div>
      <div className="container flex flex-col gap-4 px-4 py-12 md:py-24 items-center justify-center text-center">
        <div className="grid gap-2 items-center">
        </div>
        <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl lg:text-7xl">72°F</h1>
        <p className="text-xl font-medium tracking-tighter">Clear sky</p>
      </div>
    </div>
  )
}