/**
 * This code was generated by v0 by Vercel and heavily modified for reactivity.
 * @see https://v0.dev/t/nrUO8T1y5L4
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SunIcon, CloudSunIcon, CloudIcon, CloudRainIcon, CloudSnowIcon, MoonIcon, UmbrellaIcon } from "lucide-react"
import Link from "next/link"
import { ChangeEvent, InputHTMLAttributes, useState } from "react"
import { ClientForm } from "./client-form"

const icons = [SunIcon, CloudSunIcon, CloudIcon, CloudRainIcon, CloudSnowIcon, MoonIcon, UmbrellaIcon]

export function Home() {

  // Randomize the icon because that's fun
  const RandIcon = icons[Math.floor(Math.random() * icons.length)]

  return (
    <div className="container flex flex-col items-center justify-center gap-4 px-4 py-12 mx-auto text-center md:py-24">
      <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl lg:text-7xl">Weather Forecast</h1>
      <p className="max-w-[600px] text-gray-800 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
        Enter your ZIP code to get the latest weather forecast for your area.
      </p>
      {/* Because I couldn't figure out server component form routing */}
      <ClientForm>
        <RandIcon></RandIcon><span>Get Weather</span>
      </ClientForm>
    </div>
  )
}