/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TdNZKJoUKO6
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Weather() {
  return (
    <div className="bg-gray-50 py-12 lg:py-24">
      <div className="grid gap-12 px-4 lg:px-6 container lg:grid-cols-2 items-center">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tight">5-Day Forecast</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter a ZIP code to get the 5-day forecast.</p>
          <div className="flex gap-4 w-full max-w-sm">
            <Input placeholder="Enter ZIP code" />
            <Button>Submit</Button>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-0.5 items-center">
            <SunIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Clear</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudSunIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Partly Cloudy</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Cloudy</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudRainIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Rain</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudSnowIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Snow</p>
          </div>
        </div>
      </div>
      <div className="grid gap-6 px-4 lg:px-6 container lg:grid-cols-2">
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Today</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <p className="text-sm font-medium">Partly cloudy with a high of 42° and a low of 30°.</p>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <SunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Tomorrow</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Friday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Saturday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Sunday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41" />
      <path d="m17.66 17.66 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function CloudSunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v2" />
      <path d="m4.93 4.93 1.41" />
      <path d="M20 12h2" />
      <path d="m19.07 4.93-1.41 1.41" />
      <path d="M15.947 12.65a4 4 0 0-5.925-4.128" />
      <path d="M13 22H7a5 5 0 1 4.9-6H13a3 3 6Z" />
    </svg>
  )
}


function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 6.71-9h1.79a4.5 4.5 9Z" />
    </svg>
  )
}


function CloudRainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14.899A7 7 0 1 15.71 8h1.79a4.5 4.5 2.5 8.242" />
      <path d="M16 14v6" />
      <path d="M8 14v6" />
      <path d="M12 16v6" />
    </svg>
  )
}


function CloudSnowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14.899A7 7 0 1 15.71 8h1.79a4.5 4.5 2.5 8.242" />
      <path d="M8 15h.01" />
      <path d="M8 19h.01" />
      <path d="M12 17h.01" />
      <path d="M12 21h.01" />
      <path d="M16 15h.01" />
      <path d="M16 19h.01" />
    </svg>
  )
}


function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 9 1 1-9-9Z" />
    </svg>
  )
}


function UmbrellaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12a10.06 10.06 1 0 0-20 0Z" />
      <path d="M12 12v8a2 2 0 4" />
      <path d="M12 2v1" />
    </svg>
  )
}
