/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TdNZKJoUKO6
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { SunIcon, CloudSunIcon, CloudIcon, CloudRainIcon, CloudSnowIcon, MoonIcon, UmbrellaIcon } from "lucide-react"

export function Weather() {
  return (
    <div className="bg-gray-50 py-12 lg:py-24">
      <div className="grid gap-12 px-4 lg:px-6 container lg:grid-cols-2 items-center">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tight">5-Day Forecast</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter a ZIP code to get the 5-day forecast.</p>
          <div className="flex gap-4 w-full max-w-sm">
            <Input placeholder="Enter ZIP code" />
            <Button>Submit</Button>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-0.5 items-center">
            <SunIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Clear</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudSunIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Partly Cloudy</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Cloudy</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudRainIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Rain</p>
          </div>
          <div className="grid gap-0.5 items-center">
            <CloudSnowIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
            <p className="text-sm font-medium">Snow</p>
          </div>
        </div>
      </div>
      <div className="grid gap-6 px-4 lg:px-6 container lg:grid-cols-2">
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Today</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <p className="text-sm font-medium">Partly cloudy with a high of 42° and a low of 30°.</p>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <SunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Tomorrow</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Friday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Saturday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Sunday</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-1.5 items-center">
                <div className="flex items-center">
                  <UmbrellaIcon className="w-4 h-4 mr-2" />
                  <p className="text-sm">Rain likely in the morning. Partly cloudy in the afternoon. High 48°.</p>
                </div>
              </div>
              <div className="grid gap-4">
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">12:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">35°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">3:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">42°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">6:00 PM</p>
                  <div className="flex items-center justify-end">
                    <CloudSunIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Partly Cloudy</p>
                  </div>
                  <p className="text-sm">37°</p>
                </div>
                <div className="grid grid-cols-2 items-center">
                  <p className="font-medium">9:00 PM</p>
                  <div className="flex items-center justify-end">
                    <MoonIcon className="w-4 h-4 mr-2" />
                    <p className="font-medium">Clear</p>
                  </div>
                  <p className="text-sm">30°</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
